name: myFirstworkflow
on: push  
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: creating a report file
        run: echo "This is my first workflow" > report.txt

      - name: upoload reporst artifact file
        uses: actions/upload-artifact@v4
        with:
          name: report-artifact
          path: report.txt


  check_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download report artifact
        uses: actions/download-artifact@v5
        with:
          name: report-artifact
      - name: check artifacet contents
        run: cat report.txt


        
