name: myFirstworkflow
on: push  
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: git clone https://github.com/varsha-wagh-45/GitHub-Actions.git

      - name: List files in repository
        run: 
          cd GitHub-Actions
          ls -l 


        
