name: myFirstworkflow
on: push  
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: List files in repository
        run: ls -l 


        
