name: myFirstworkflow
on: push  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: aws key setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: aws cli check
        run: aws --version

      - name: s3 list buckets
        run: aws s3 ls
      


  